{"name": "test_specific_feature", "status": "failed", "statusDetails": {"message": "Failed: Test failed with message: 先前的充值申请正在处理中，请勿重复提交！#Do Not Do Payment Again Before Your Order Is Finished#還有充值申請正在處理中，請稍後再提交。#อย่าชำระเงินอีกก่อนที่คำสั่งซื้อของคุณจะเสร็จสิ้น#Não faça o pagamento novamente antes que seu pedido seja concluído", "trace": "@pytest.mark.asyncio\n    async def test_specific_feature():\n        playwright, browser, context = await setup_browser()  # 使用默认设备iPhone 11\n        test_failed = False\n        fail_message = \"\"\n        try:\n            page = await load_and_check_page(context)\n            print(\"Page loaded successfully.\")\n    \n            await login(page, \"all24042501\", \"396012\")  # 使用公共登录函数\n    \n            with step(\"导航到个人中心\"):\n                await page.click(\"div.label:has-text('個人中心')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_navigate_to_personal_center\")\n    \n            with step(\"点击存款\"):\n                await page.click(\"div.label:has-text('存款')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_click_deposit\")\n    \n            with step(\"选择数字乐\"):\n                await page.click(\"div.am-list-content:has-text('數字樂')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_select_bank_transfer\")\n    \n            with step(\"输入充值金额\"):\n                await page.fill(\"input#chargeAmount.fc-red\", \"100\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_enter_deposit_amount\")\n    \n            async def handle_response(response):\n                if response.url == \"https://wap-q6.qbpink01.com/payment/frontend/doPay\":\n                    json_data = await response.json()\n                    print(f\"Response from doPay: {json_data}\")\n                    if json_data.get('code') == '2313':\n                        nonlocal test_failed, fail_message\n                        test_failed = True\n                        fail_message = f\"Test failed with message: {\n                            json_data.get('msg')}\"\n    \n            page.on('response', handle_response)\n    \n            with step(\"点击下一步按钮\"):\n                await page.click(\"a.submitBtn:has-text('下一步')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_confirm_deposit\")\n    \n            with step(\"确认充值完成\"):\n                await page.click(\"a:has-text('已完成充值')\")\n                await asyncio.sleep(2)\n                await take_screenshot_and_attach(page, \"after_confirm_deposit\")\n    \n        except Exception as e:\n            print(f\"An error occurred: {e}\")\n            if page is not None:\n                await take_screenshot_and_attach(page, \"error_during_test\")\n        finally:\n            # 注销监听器\n            page.remove_listener('response', handle_response)\n            if browser is not None:\n                await browser.close()\n            if playwright is not None:\n                await playwright.stop()\n            if test_failed:\n>               pytest.fail(fail_message)\nE               Failed: Test failed with message: 先前的充值申请正在处理中，请勿重复提交！#Do Not Do Payment Again Before Your Order Is Finished#還有充值申請正在處理中，請稍後再提交。#อย่าชำระเงินอีกก่อนที่คำสั่งซื้อของคุณจะเสร็จสิ้น#Não faça o pagamento novamente antes que seu pedido seja concluído\n\nbasic_module\\test_digital music.py:72: Failed"}, "steps": [{"name": "导航到个人中心", "status": "passed", "attachments": [{"name": "after_navigate_to_personal_center", "source": "97676324-95a9-4ab1-a97b-ec5fa96329bc-attachment.png", "type": "image/png"}], "start": 1716865755464, "stop": 1716865759111}, {"name": "点击存款", "status": "passed", "attachments": [{"name": "after_click_deposit", "source": "069899c7-ec44-4db7-9be0-f8609fec9062-attachment.png", "type": "image/png"}], "start": 1716865759111, "stop": 1716865761288}, {"name": "选择数字乐", "status": "passed", "attachments": [{"name": "after_select_bank_transfer", "source": "820587e0-8a3a-4a1f-9e41-e3e7e5223bfe-attachment.png", "type": "image/png"}], "start": 1716865761288, "stop": 1716865763461}, {"name": "输入充值金额", "status": "passed", "attachments": [{"name": "after_enter_deposit_amount", "source": "369547e0-63fe-4616-b862-c661ee707552-attachment.png", "type": "image/png"}], "start": 1716865763461, "stop": 1716865765579}, {"name": "点击下一步按钮", "status": "passed", "attachments": [{"name": "after_confirm_deposit", "source": "ee0ebead-653c-405e-969d-fb174fb0932b-attachment.png", "type": "image/png"}], "start": 1716865765584, "stop": 1716865767752}, {"name": "确认充值完成", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.click: Timeout 30000ms exceeded.\nCall log:\nwaiting for locator(\"a:has-text('已完成充值')\")\n\n", "trace": "  File \"C:\\Users\\luekc\\Desktop\\Q6\\basic_module\\test_digital music.py\", line 56, in test_specific_feature\n    await page.click(\"a:has-text('已完成充值')\")\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\async_api\\_generated.py\", line 9444, in click\n    await self._impl_obj.click(\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 753, in click\n    return await self._main_frame.click(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 488, in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\luekc\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 513, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1716865767752, "stop": 1716865797771}], "attachments": [{"name": "error_during_test", "source": "507d35f7-b20b-40bc-a3cd-79b291ddd5c1-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "9749f8a2-b910-48d2-b0a4-68ae9389ba5b-attachment.txt", "type": "text/plain"}], "start": 1716865740098, "stop": 1716865798104, "uuid": "db5349b8-992b-4c48-848c-e72b15ea88b2", "historyId": "25d87ba0cfa6d2772725fc948070e326", "testCaseId": "25d87ba0cfa6d2772725fc948070e326", "fullName": "basic_module.test_digital music#test_specific_feature", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "basic_module"}, {"name": "suite", "value": "test_digital music"}, {"name": "host", "value": "Luke"}, {"name": "thread", "value": "17004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "basic_module.test_digital music"}]}